### PR TITLE
Recombine divergent leaf nodes using migration

### PR DESCRIPTION
**Pull request by dhruvkb**
## Description

CI tests are failing because of two migrations numbered 48 that creates two leaf nodes. This PR introduces migration 49 that recombines the leaves into a single terminal node.

## Testing Instructions

CI should pass.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by obulat — APPROVED** [review]
Did you run `makemigrations -merge` to fix this?
CI is passing!

**Comment by dhruvkb** [comment]
Yes @obulat. Another thing we could do is edit the migrations to edit their dependency but it's generally recommended not to edit migrations. These migrations haven't been deployed so we could do this if we like.

**Comment by sarayourfriend** [comment]
How can we prevent this? Is there any way we can ensure PRs with migrations are always rebased before merging? Could we run an action triggered by pushes that introduce new migrations using https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-affects-specific-files and the iterate through all open, non-draft PRs and request changes on them if there is a migration in them?

We'd also need a similar job in the CI + CD workflow to check for migration conflicts against main any time the PR is pushed to.

**Review by sarayourfriend — APPROVED** [review]

**Comment by sarayourfriend** [comment]
I opened an issue to address my comment above: https://github.com/WordPress/openverse-api/issues/811

**Comment by dhruvkb** [comment]
Damn, I opened #812. Going to close mine as a duplicate.

**Pull request merged**
