### PR TITLE
Add terms of service to included files for docker image

### PR DESCRIPTION
**Pull request by AetherUnbound**
## Description

This PR addresses a minor issue wherein the terms of service document was not available within the Docker container, and thus couldn't be served by nginx in production.

## Testing Instructions

1. Run `just build`
1. Run `docker run --entrypoint='' --rm -it openverse-api:latest ls`
1. Observe that `terms_of_service.html` is present within the container. 

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by dhruvkb** [comment]
While this PR does work as intended, based on the minified nature of the file and this comment
https://github.com/WordPress/openverse-api/blob/4c308ccf8fad3040cac07ddc535573b8263d624a/api/terms_of_service.html#L2
it seems like the file is auto-generated. I'm not sure if it should even be tracked in VCS.

**Comment by AetherUnbound** [comment]
Here's the file in prod now: https://api.openverse.engineering/terms_of_service.html
It looks like there are a bunch of places where we could change CC Catalog as well. That said, based on our infrastructure repository, the file is served directly from the repo (it's not minified or pulled in from anywhere). Do you have any thoughts or suggestions as to where we should move this?

**Comment by dhruvkb** [comment]
Imo, we should convert this into a markdown file and serve it inside the ReDoc view itself, similar to how we have these other sections in the API documentation.

Screenshot 2022-05-03 at 5 26 46 PM

This has the main advantage of being immediately discoverable (lives with the API docs) and very readable in both the web UI as well as in the raw Markdown format (which the minified HTML lacks). Also, it can be Git-tracked which is not true for minified auto-generated HTML files.

**Comment by sarayourfriend** [comment]
That's a great idea Dhruv!

**Comment by AetherUnbound** [comment]
Agreed! But bummer, the `terms_of_service` field explicitly has to be a URL: https://swagger.io/specification/
Since we have the sections you described as part of our docs' `README.md` file, we'll have to find another way for Swagger to serve this.

**Comment by sarayourfriend** [comment]
Can't it point to a URL... that it itself generates? Or... :thinking: It could just be the fully qualified URL to the production place where it _will_ exist?

**Comment by AetherUnbound** [comment]
Yea, exactly that! I just need to figure out how to get a "regular page" up in Swagger, I haven't used it very much 😅

**Comment by sarayourfriend** [comment]
Oh you know, I was assuming we'd add it to the MyST docs, not the swagger docs, sorry!

**Comment by AetherUnbound** [comment]
> Oh you know, I was assuming we'd add it to the MyST docs, not the swagger docs, sorry!

🤦🏼‍♀️ _I_ was assuming it **had** to be in the swagger docs! Since it's literally just a link, we could 1000% make it the MyST docs! So much easier 🚀

**Comment by sarayourfriend** [comment]
Nice!

**Comment by AetherUnbound** [comment]
The changes are pretty significant and result in a very different PR, so I'm going to close this one and open a new one.

**Pull request closed without merging**
