### PR TITLE
Use `::` over `cast` in audioset_view

### LINKED ISSUE #467: Use `::` over `cast` in audioset_view
## Problem

We have a few different forms of the `audioset_view` definition (see WordPress/openverse-catalog#320).

## Description

These should be unified so all definitions are the same, even if [`cast` and `::` serve the same purpose](https://www.postgresql.org/docs/13/sql-expressions.html#SQL-SYNTAX-TYPE-CASTS). That syntax also already exists in the [ingestion server mock schema DDL](https://github.com/WordPress/openverse-api/blob/a7aa53ffc5f9d3b8b6bebf9dbacba248623a5a61/ingestion_server/test/mock_schemas/audioset_view.sql#L22), so we can apply that to the `load_sample_data.sh` script.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by parthpatel9414**
Fixes #467

## Fixes

Fixes #[648] by @AetherUnbound 

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by AetherUnbound** [comment]
Thanks for getting this work started @parthpatel9414! While the error messages aren't super clear, I am seeing this [in the logs](https://github.com/WordPress/openverse-api/runs/6151021640?check_suite_focus=true):
```
DROP VIEW
NOTICE:  view "audioset_view" does not exist, skipping
ERROR:  type "foreign_identifier" does not exist
LINE 4: ...et ->> 'foreign_identifier'   :: varchar(1000) :: foreign_id...
                                                             ^
```

I think there are a couple of things going on here:
1. The `::` syntax can only be used as a replacement for `cast(x as y)` (e.g. `x::y`). We can't use it to replace an *alias*, which is the second `as` on this line. This is discussed in the PostgreSQL documentation

    > By default, a cast can be invoked only by an explicit cast request, that is an explicit CAST(x AS typename) or x::typename construct. _[Source](https://www.postgresql.org/docs/current/sql-createcast.html)_

    And

    > Just as in a table, every output column of a SELECT has a name. In a simple SELECT this name is just used to label the column for display, but when the SELECT is a sub-query of a larger query, the name is seen by the larger query as the column name of the virtual table produced by the sub-query. To specify the name to use for an output column, write AS output_name after the column's expression. (You can omit AS, but only if the desired output name does not match any PostgreSQL keyword (see [Appendix C](https://www.postgresql.org/docs/current/sql-keywords-appendix.html)). _[Source](https://www.postgresql.org/docs/current/sql-select.html)_

2. Another factor in play is the order of operations. When I tested this locally after changing the second `::` to `as`, I got this error:

    ```
    ERROR:  invalid input syntax for type integer: "filesize"
    LINE 10: audio_set ->> 'filesize'             :: integer       as fil...
                                                     ^
    ```

    It looks like this can be resolved by wrapping the JSON access in parenthesis: `(audio_set ->> 'filesize')::integer as filesize`. I assume this error arises because Postgres is trying to convert the string `'filesize'` as an integer rather than casting the field.


Hope this all makes sense, let us know if you have any questions or run into any difficulties!

**Comment by parthpatel9414** [comment]
> Thanks for getting this work started @parthpatel9414! While the error messages aren't super clear, I am seeing this [in the logs](https://github.com/WordPress/openverse-api/runs/6151021640?check_suite_focus=true):
> 
> ```
> DROP VIEW
> NOTICE:  view "audioset_view" does not exist, skipping
> ERROR:  type "foreign_identifier" does not exist
> LINE 4: ...et ->> 'foreign_identifier'   :: varchar(1000) :: foreign_id...
>                                                              ^
> ```
> 
> I think there are a couple of things going on here:
> 
>     1. The `::` syntax can only be used as a replacement for `cast(x as y)` (e.g. `x::y`). We can't use it to replace an _alias_, which is the second `as` on this line. This is discussed in the PostgreSQL documentation
>        > By default, a cast can be invoked only by an explicit cast request, that is an explicit CAST(x AS typename) or x::typename construct. _[Source](https://www.postgresql.org/docs/current/sql-createcast.html)_
>        
>        
>        And
>        > Just as in a table, every output column of a SELECT has a name. In a simple SELECT this name is just used to label the column for display, but when the SELECT is a sub-query of a larger query, the name is seen by the larger query as the column name of the virtual table produced by the sub-query. To specify the name to use for an output column, write AS output_name after the column's expression. (You can omit AS, but only if the desired output name does not match any PostgreSQL keyword (see [Appendix C](https://www.postgresql.org/docs/current/sql-keywords-appendix.html)). _[Source](https://www.postgresql.org/docs/current/sql-select.html)_
> 
>     2. Another factor in play is the order of operations. When I tested this locally after changing the second `::` to `as`, I got this error:
>        ```
>        ERROR:  invalid input syntax for type integer: "filesize"
>        LINE 10: audio_set ->> 'filesize'             :: integer       as fil...
>                                                         ^
>        ```
>        
>        
>            
>              
>            
>        
>              
>            
>        
>            
>          
>        It looks like this can be resolved by wrapping the JSON access in parenthesis: `(audio_set ->> 'filesize')::integer as filesize`. I assume this error arises because Postgres is trying to convert the string `'filesize'` as an integer rather than casting the field.
> 
> 
> Hope this all makes sense, let us know if you have any questions or run into any difficulties!

Hello @AetherUnbound ,
Thanks for the explanation and sorry for being late to get back to you.
I try and complete the issue by end of this week. 

Thank you again.

**Comment by AetherUnbound** [comment]
Hey @parthpatel9414, just checking in! Do you still have time to tackle this work? We can try and get it across the finish line if not 🙂

**Comment by AetherUnbound** [comment]
Hmm, it looks like #693 unfortunately didn't prevent the docs preview workflow from running @dhruvkb 😞

**Review by obulat — APPROVED** [review]
It all looks well, @parthpatel9414. Thank you for your contribution!

**Review by stacimc — APPROVED** [review]
Looks good! My understanding is the docs preview is not an issue and that it shouldn't have run here, so this should be okay to merge 🤔

**Pull request merged**
