### PR TITLE
Add a recipe `ps` that runs after `up`

### LINKED ISSUE #952: `just` command to list services and their ports
## Problem

It can be a bit difficult to grok which services the API `just up` command starts and waht ports they are on.

## Description

Add a new just command which lists running services and their ports. Perhaps something like this output:

```bash
openverse-api
❯ just list-services
4 Services are running:
- Service name: http://localhost/:{port}
- Service name: http://localhost/:{port}
- Service name: http://localhost/:{port}
- Service name: http://localhost/:{port}
```

We could run this automatically after `just up` as well to make it really clear to users.

As far as implementing this goes, we'll want to make sure to list the services programmatically and not via hardcoded strings so it's resilient to port changes or errors. For example perhaps we could parse `docker ps` and prettify the output, or some other approach.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by dhruvkb**
## Fixes

Fixes #952 by @zackkrida 

## Description

This PR adds a recipe `ps` that invokes a Python script to parse the output of `docker-compose ps` and generate a list of URLs for each running service.

It currently does not see to verify if something is indeed running at that URLs (notably API port 50230, which is usually bound but rarely used).

## Testing Instructions

0. Checkout this PR and run `just up`.
1. See the list of services being printed automatically after `up` is complete.
2. Run `just ps`.
3. See the list of services.

## Screenshots

Screenshot 2022-09-28 at 5 41 56 AM

In iTerm2, these URLs are clickable with <kbd>Cmd</kbd> held down, super helpful!

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by stacimc — COMMENTED** [review]
I couldn't quite get this working for me -- it looks like docker-compose version issues. Out of the box I get this error:

```
raise JSONDecodeError("Expecting value", s, err.value) from None
```

because the result from `get_ps()` is an empty string. From a brief look, it looks like. `--format json` is supported by `docker compose ps` but not `docker-compose ps`? 🤔

I played around with this a little and when I update the [justfile here](https://github.com/WordPress/openverse-api/blob/main/justfile#L40) to use `docker compose`, I'm able to get past the first error and see results from `get_ps`. Now, though, I'm seeing:

```
File "<..>/openverse-api/scripts/ps.py", line 70, in parse_ps
    for publisher in publishers:
TypeError: 'NoneType' object is not iterable
```

I have `docker-compose version 1.29.2`, `Docker Compose version v2.6.0`

**Comment by dhruvkb** [comment]
@stacimc you might be right, I have `docker-compose` and `docker compose` set to the same thing! This means that this PR will not work for anyone using the `docker-compose` v1.

```shell
$ docker-compose --version
Docker Compose version v2.10.2

$ docker compose version
Docker Compose version v2.10.2
```

**Comment by zackkrida** [comment]
@dhruvkb both my `docker compose` and `docker-compose` are version `2.10.2` yet I still see this error:

```shell
openverse-api on just_ps +/- [$] took 3m18s
❯ just ps
Traceback (most recent call last):
  File "/Users/zackkrida/Code/openverse/openverse-api/scripts/ps.py", line 85, in <module>
    print_ps()
  File "/Users/zackkrida/Code/openverse/openverse-api/scripts/ps.py", line 80, in print_ps
    for service in parse_ps():
  File "/Users/zackkrida/Code/openverse/openverse-api/scripts/ps.py", line 65, in parse_ps
    for publisher in publishers:
TypeError: 'NoneType' object is not iterable
error: Recipe `ps` failed on line 56 with exit code 1
```

**Comment by dhruvkb** [comment]
@zackkrida can you post the output of the following command?
```bash
$ docker compose ps --format json
```

Technically the value of `Publishers` in the JSON can be `null`, which would explain the error you're seeing but all our services have either expose a port or bind to a port on the host so that shouldn't be happening.

**Comment by krysal** [comment]
Hey @dhruvkb, I'm checking on draft PRs. Is there anything blocking you from completing the PR? Should be closed or can be resumed soon?

**Comment by dhruvkb** [comment]
I'm waiting for @zackkrida's response to [this comment](https://github.com/WordPress/openverse-api/pull/959#issuecomment-1271068129). That'll help identify the difference in the JSON that's causing the error.

**Comment by zackkrida** [comment]
@dhruvkb here is the output:

```json
[
  {
    "ID": "c2f1d732e98379418a938acd4c14d62030e9b777dc98469bf25f52552aadb92b",
    "Name": "openverse-api_cache_1",
    "Command": "docker-entrypoint.sh redis-server",
    "Project": "openverse-api",
    "Service": "cache",
    "State": "exited",
    "Health": "",
    "ExitCode": 255,
    "Publishers": [
      {
        "URL": "0.0.0.0",
        "TargetPort": 6379,
        "PublishedPort": 50263,
        "Protocol": "tcp"
      }
    ]
  },
  {
    "ID": "ebf9c9d88432c0ed8e6c17bfc69e24d7a2c7b4d2e17ab27f2e85962f11685a10",
    "Name": "openverse-api_db_1",
    "Command": "docker-entrypoint.sh postgres",
    "Project": "openverse-api",
    "Service": "db",
    "State": "exited",
    "Health": "",
    "ExitCode": 255,
    "Publishers": [
      {
        "URL": "0.0.0.0",
        "TargetPort": 5432,
        "PublishedPort": 50254,
        "Protocol": "tcp"
      }
    ]
  },
  {
    "ID": "fa5ae4ff3231abeef55d2d3068770dab1aec5f1aa7939c9e82aa6fc2bd33270c",
    "Name": "openverse-api_es_1",
    "Command": "/bin/tini -- /usr/local/bin/docker-entrypoint.sh eswrapper",
    "Project": "openverse-api",
    "Service": "es",
    "State": "exited",
    "Health": "",
    "ExitCode": 255,
    "Publishers": [
      {
        "URL": "0.0.0.0",
        "TargetPort": 9200,
        "PublishedPort": 50292,
        "Protocol": "tcp"
      },
      {
        "URL": "",
        "TargetPort": 9300,
        "PublishedPort": 0,
        "Protocol": "tcp"
      }
    ]
  },
  {
    "ID": "3e2356c09bbe378db708515f59f332ca3735e8edbc15ae5a0fd761e6669de3fa",
    "Name": "openverse-api_indexer_worker_1",
    "Command": "gunicorn -c ./gunicorn_worker.conf.py",
    "Project": "openverse-api",
    "Service": "indexer_worker",
    "State": "exited",
    "Health": "",
    "ExitCode": 255,
    "Publishers": [
      {
        "URL": "",
        "TargetPort": 8001,
        "PublishedPort": 0,
        "Protocol": "tcp"
      },
      {
        "URL": "",
        "TargetPort": 8002,
        "PublishedPort": 0,
        "Protocol": "tcp"
      }
    ]
  },
  {
    "ID": "ff866d680ba45a63c538c5f26a0d7461e0d4ac665ce40a4fd4a8e0363f8f1fb4",
    "Name": "openverse-api_ingestion_server_1",
    "Command": "gunicorn -c ./gunicorn.conf.py",
    "Project": "openverse-api",
    "Service": "ingestion_server",
    "State": "exited",
    "Health": "",
    "ExitCode": 255,
    "Publishers": [
      {
        "URL": "0.0.0.0",
        "TargetPort": 8001,
        "PublishedPort": 50281,
        "Protocol": "tcp"
      },
      {
        "URL": "",
        "TargetPort": 8002,
        "PublishedPort": 0,
        "Protocol": "tcp"
      }
    ]
  },
  {
    "ID": "b795ed180a4a6d9c12457215189387890c6ba9fd78a41b4f439c72aa1b0ab371",
    "Name": "openverse-api_proxy_1",
    "Command": "/docker-entrypoint.sh nginx -g 'daemon off;'",
    "Project": "openverse-api",
    "Service": "proxy",
    "State": "exited",
    "Health": "",
    "ExitCode": 255,
    "Publishers": [
      {
        "URL": "",
        "TargetPort": 80,
        "PublishedPort": 0,
        "Protocol": "tcp"
      },
      {
        "URL": "0.0.0.0",
        "TargetPort": 9080,
        "PublishedPort": 50200,
        "Protocol": "tcp"
      },
      {
        "URL": "0.0.0.0",
        "TargetPort": 9443,
        "PublishedPort": 50243,
        "Protocol": "tcp"
      }
    ]
  },
  {
    "ID": "6b66d48c2388719d5e776cd4f014db637e155705c311c75bc94108032ec868cf",
    "Name": "openverse-api_thumbnails_1",
    "Command": "/usr/local/bin/imaginary -enable-url-source -forward-headers User-Agent",
    "Project": "openverse-api",
    "Service": "thumbnails",
    "State": "exited",
    "Health": "",
    "ExitCode": 255,
    "Publishers": [
      {
        "URL": "",
        "TargetPort": 8222,
        "PublishedPort": 0,
        "Protocol": "tcp"
      },
      {
        "URL": "",
        "TargetPort": 9000,
        "PublishedPort": 0,
        "Protocol": "tcp"
      }
    ]
  },
  {
    "ID": "ef52be6a30eaf5331146c3c3e3d037d072459a65b5962a8cd15d201a69927fa0",
    "Name": "openverse-api_upstream_db_1",
    "Command": "docker-entrypoint.sh postgres",
    "Project": "openverse-api",
    "Service": "upstream_db",
    "State": "exited",
    "Health": "",
    "ExitCode": 255,
    "Publishers": [
      {
        "URL": "",
        "TargetPort": 5432,
        "PublishedPort": 0,
        "Protocol": "tcp"
      }
    ]
  },
  {
    "ID": "ecea6ee5b704942c358449dd448924a2b8aca657d92871779943ee96d158bb1e",
    "Name": "openverse-api_web_1",
    "Command": "./run.sh python manage.py runserver 0.0.0.0:8000",
    "Project": "openverse-api",
    "Service": "web",
    "State": "exited",
    "Health": "",
    "ExitCode": 255,
    "Publishers": [
      {
        "URL": "0.0.0.0",
        "TargetPort": 3000,
        "PublishedPort": 50230,
        "Protocol": "tcp"
      },
      {
        "URL": "0.0.0.0",
        "TargetPort": 8000,
        "PublishedPort": 50280,
        "Protocol": "tcp"
      }
    ]
  }
]
```

**Comment by dhruvkb** [comment]
Since none of those items has `Publishers` not present or empty or `null`, it's unclear why 
```
    for publisher in publishers:
TypeError: 'NoneType' object is not iterable
```
would appear.

**Pull request closed without merging**
