### PR TITLE
Add back and correct "resendoauthverification" command

### LINKED ISSUE #770: Sent API registration emails contained a typo
We recently used a one-off script to send emails to users who had registered for the Openverse API during a time period in which verification emails were broken. Unfortunately, the emails we sent contained broken link with a url with two slashes, like so:

```
                      error here: ↓
https://api.openverse.engineering//v1/auth_tokens/verify/{mytoken}
```

We should most likely:

1. Reintroduce the one-off script (it was removed in this PR: https://github.com/WordPress/openverse-api/pull/768)
2. Fix the duplicated slash
3. **Bonus**: The emails were shown to be sent from 'noreply'; ideally we could set a name like 'Openverse API Team' or something in the code. Here's how it looked in Gmail:
  CleanShot 2022-06-24 at 12 42 30@2x

Edit: As @sarayourfriend indicated, we can identify the users we emailed in production under the `resendoauthverification:processed` redis key.

### PR DESCRIPTION
**Pull request by sarayourfriend**
Fixes #770 by @zackkrida 

## Description
Corrects the email. I took a shot at the text of the corrected email but please feel free to offer better wording if you can think of any!

## Testing instructions
Follow instructions from the original PR for testing locally: https://github.com/WordPress/openverse-api/pull/694

Note also that CI should pass.

### CODE REVIEW

**Review by zackkrida — APPROVED** [review]
LGTM! The copy is good, thank you.

**Comment by zackkrida** [comment]
@obulat and @krysal can you review this today or tomorrow so we can resend these emails this week?

**Review by krysal — APPROVED** [review]
I ran the `dry` version first and then the one with the `--no-dry_run` flag and I got different outputs. Is this expected?

Running `just dj resendoauthverification`:

```
The following applications had email verifications sent.                                                                                              

Application name: My test project
Cleaned related application count: 3
Cleaned related verification count: 3
Cleaned related registration count: 3


Application name: My test project2
Cleaned related application count: 0
Cleaned related verification count: 0
Cleaned related registration count: 0


Application name: My test project3
Cleaned related application count: 1
Cleaned related verification count: 1
Cleaned related registration count: 1

The above was a dry run and no records were actually affected.
```

Running `just dj resendoauthverification --no-dry_run`:

```
The following applications had email verifications sent.                                                                                              

Application name: My test project
Cleaned related application count: 3
Cleaned related verification count: 0
Cleaned related registration count: 3


Application name: My test project2
Cleaned related application count: 0
Cleaned related verification count: 0
Cleaned related registration count: 0


Application name: My test project3
Cleaned related application count: 1
Cleaned related verification count: 0
Cleaned related registration count: 1
```

I verified the link sent in the email and it works. It would be nice to see a unit test for it since the actual error was there. I'm less concerned as this has been already run in production, so approving to unblock.

**Comment by sarayourfriend** [comment]
I do not know why that discrepancy exists. Reading through the code it doesn't seem like it should, the counts for each thing happen independent of the deletions and deleting one thing or another doesn't make the verifications query work different, at least not in any way that is evident to me by reading the code...

> It would be nice to see a unit test for it since the actual error was there

I started to add a unit test that actually made a request with the URL... but I wasn't sure how to do that without having to spin up an API :thinking: If we use the RequestFactory approach it wouldn't _really_ be all that useful, I don't think. We could assert in a regex or something that there are no double `/`s. Would that work for you?

**Comment by krysal** [comment]
> We could assert in a regex or something that there are no double /s. Would that work for you?

That sounds good!

**Comment by sarayourfriend** [comment]
Added the unit test. If you put back the extra `/` they will fail. Thanks for the suggestion, Krystle!

**Pull request merged**
