### PR TITLE
Catch struct errors in `watermark/` endpoint

### LINKED ISSUE #849: `piexif.dump` errors are not safely handled
## Sentry link

https://sentry.io/share/issue/a80d52de7f89436586ed0250cd0a32d2/

## Description

The call to `piexif.dump` should be wrapped in a `try/except` to prevent these errors in the watermark endpoint.

## Reproduction

Visit https://api-dev.openverse.engineering/v1/images/a913fde1-d524-4059-bd4f-9bd687578cc3/watermark/ to see an example of this failure.

### PR DESCRIPTION
**Pull request by krysal**
## Fixes

Fixes #849 by @sarayourfriend 

## Description

This PR:
- catches struct errors from `piexif.load` function. The last release of this library is from July 2019, so it will need a replacement sooner than later
- sets environment variables to enable the watermark endpoint locally and name the environment properly

I was writing a test but it wasn't failing even before the fix and it's taking too much time to mock. I haven't found a way to reproduce the error locally so hoping just to catch the exception to solve the Sentry alerts.

<details>

<summary>Non failing test</summary>

```python 
# Adding to file: api/test/unit/utils/watermark_test.py

import struct
from io import BytesIO
from PIL import Image
from unittest import mock
from catalog.api.utils.watermark import _open_image

...

def test_catch_struct_errors_from_piexif(requests):
    with mock.patch("PIL.Image.open") as open_mock, mock.patch("piexif.load") as load_mock:
        img_mock = Image.open(BytesIO(_MOCK_IMAGE_BYTES))
        img_mock.info["exif"] = "bad_info"
        open_mock.return_value = img_mock
        load_mock.side_effect = struct.error('unpack requires a buffer of 2 bytes')

        img, exif = _open_image("http://example.com/")

    assert img is not None
    assert exif is None
```

</details>

## Testing Instructions

Visit the `watermark/` endpoint of any image, eg. http://localhost:50280/v1/images/dba4f725-9370-4442-8db1-522e788d6c55/watermark/

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by sarayourfriend** [comment]
> The last release of this library is from July 2019, so it will need a replacement sooner than later

We could switch to Pillow for this, I would think. We already use it elsewhere, and it is a massively popular library. (For another issue, of course.)

**Review by sarayourfriend — CHANGES_REQUESTED** [review]
Can you add a unit test to exercise this change? Otherwise it LGTM.

**Comment by krysal** [comment]
@sarayourfriend 

> Can you add a unit test to exercise this change? Otherwise it LGTM.

As I mentioned at the beginning, I tried but couldn't trigger the same issue we are getting from Sentry 😅 Do you see anything that needs to change in the test I tried to include? It never fails so it's basically useless in that way. I used the "private" `_open_image` function because the public `watermark` was requiring more mocking, and the problematic code is in on the first one anyway.

**Comment by sarayourfriend** [comment]
@krysal I totally glossed over the collapsed test code in the description, sorry.

I suspect the `Image.open` mock is incorrect. Because the module imports it as `from PIL import Image` you'd need to mock Image in the watermark module itself, I think? Python import mocks always take a bit of fiddling for me to figure out too :sweat: 

I think it's fine to test against the private method on this case, FWIW, given it's a weird edge case error. It'd be annoying if we refactored the method but we'll want to be careful with this one anyway.

**Comment by sarayourfriend** [comment]
Taking a look at this now locally. I'm wrong about the mocks, you've got them correct. It's just doing the thing that I cannot figure out how to stop MagicMock from doing (which I never seem to remember it doing before), which is that instead of actually returning the `.return_value` set on `open` it's just returning a new MagicMock instance :angry: I ran into this before with something else. I think it has something to do with `auto_spec`. I'll see if I can figure it out.

**Comment by sarayourfriend** [comment]
Okay, actually everything was fine _except_ a very subtle thing. Here's the test that works (I confirmed with `breakpoint` that it goes to the error handling, I wish there was a better way to verify the test was working as expected):

```py

def test_catch_struct_errors_from_piexif(requests):
    img_mock = Image.open(BytesIO(_MOCK_IMAGE_BYTES))
    img_mock.info["exif"] = "bad_info"

    with mock.patch("PIL.Image.open") as open_mock, mock.patch("piexif.load") as load_mock:
        open_mock.return_value = img_mock
        load_mock.side_effect = struct.error('unpack requires a buffer of 2 bytes')

        img, exif = _open_image("http://example.com/")

    assert img is not None
    assert exif is None
```

I guess the issue was that because we were mocking `PIL.Image.open`, the mocked version of the method was also being used to create the `img_mock`. Moving it outside the context manager of the `mock.patch` for that method fixes the test so that it actually exercises the error condition.

**Review by AetherUnbound — APPROVED** [review]
LGTM

**Review by sarayourfriend — APPROVED** [review]
:rocket:

**Review by stacimc — APPROVED** [review]
LGTM! Testing discussion is also very interesting and helpful :)

**Pull request merged**
