### PR TITLE
Update sample data for images with missing columns filled

### LINKED ISSUE #270: Update sample data
## Problem

The API has support for `filesize` and `filetype` fields after WordPress/openverse#266. These fields are not populated completely for image and audio samples.

| Media type | `filesize` | `filetype` |
|-|-|-|
| Image | ❌ | ❌ |
| Audio | ❌ | ✅ |

We also need to make sure these changes are reflected in the new data:

- https://github.com/WordPress/openverse-catalog/issues/263
- https://github.com/WordPress/openverse-catalog/issues/292

## Description

The presence of this data can help to ensure that these fields are working as expected.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by krysal**
## Fixes

Fixes #270 by @dhruvkb 

## Description

This PR adds new sample data for images with `category`, `filesize` and `filetype` columns filled. The data comes from the recently updated Flickr and StockSnap scripts (2500 rows each) using this query on the catalog DB:

```sql
SELECT
	identifier, created_on, updated_on, ingestion_type, provider, source, 
	foreign_identifier, foreign_landing_url, url, thumbnail, width, height, filesize
	license, license_version, creator, creator_url, title, meta_data, tags, watermarked,
	last_synced_with_source, removed_from_source, filetype, category, standardized_popularity
FROM (
	SELECT *, ROW_NUMBER() OVER (
		PARTITION BY provider ORDER BY standardized_popularity DESC
	) AS row_num
	FROM image_view
) AS T
WHERE row_num <= 2500;
```

I also updated the tests accordingly. The only test I'm still not sure how was produced/mocked before is `test_dead_links_are_correctly_filtered`, is the only one that still fails. Perhaps @dhruvkb do you have a suggestion for this? Would be really useful.

## Testing Instructions

See the results of the test running:
```
just api-test
``` 
And/or explore the new data.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by AetherUnbound — APPROVED** [review]
This looks great! I tried running the API tests, but I'm getting the following error:
```
search_with_dead_links = <function search_with_dead_links.<locals>._search_with_dead_links at 0x7fa04a094dc0>, search_without_dead_links = <function search_without_dead_links.<locals>._search_without_dead_links at 0x7fa04a094c10>

    def test_dead_links_are_correctly_filtered(
        search_with_dead_links, search_without_dead_links
    ):
        """
        Test the results for the same query with and without dead links are
        actually different.
    
        We use the results' id to compare them.
        """
        data_with_dead_links = search_with_dead_links(q="*", page_size=100)
        data_without_dead_links = search_without_dead_links(q="*", page_size=100)
    
        comparisons = []
        for result_1 in data_with_dead_links["results"]:
            for result_2 in data_without_dead_links["results"]:
                comparisons.append(result_1["id"] == result_2["id"])
    
        # Some results should be different
        # so we should have less than 100 True comparisons
>       assert comparisons.count(True) < 100
E       assert 100 < 100
E        +  where 100 = <built-in method count of list object at 0x7fa049f02dc0>(True)
E        +    where <built-in method count of list object at 0x7fa049f02dc0> = [True, False, False, False, False, False, ...].count
```

It looks unrelated, but just posting it in case it isn't. Otherwise :heavy_check_mark: !

**Review by zackkrida — APPROVED** [review]
This is such a big help 😄 Awesome! seeing the same error reported by others that seems related, as it's mentioned in other PRs.

**Review by dhruvkb — APPROVED** [review]
It's really great to have new sample data with as many cells filled as possible. Although we need to figure out why CI failed, this is huge. Thank you @krysal.

**Comment by dhruvkb** [comment]
As for the failing test, it relies on actual web requests to determine which links are dead and which aren't. The best way to handle such tests would be to mock the requests but that is not something that can be done in integration tests that only have client-side access. I'd resolve this by moving changing this test to one that uses Django's testing library to mock the `validate_images` function on the server.

**Comment by krysal** [comment]
I didn't notice this broke a test of the analytic server. Thank you again @dhruvkb for the help with those!

**Pull request merged**
