### PR TITLE
Add docker volumes for local development

### LINKED ISSUE #407: Docker volumes for local development
## Problem

Once the docker-compose stack is taken down, the API, catalog, and Elasticsearch all need to be re-initialized once it is started up again.

## Description

We should add named docker volumes to these 3 services so the stack can be safely restarted without losing data.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by AetherUnbound**
## Fixes

Fixes #407 by @AetherUnbound

## Description

This PR adds docker volumes for both DBs and ES.

## Testing Instructions

1. `just init`
1. `just down`
1. `just up` - databases should be migrated and indices should still exist in ES

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by sarayourfriend — COMMENTED** [review]
Unfortunately I can't fully test this because I'm running into this issue, causing the web container to never be healthy and so `just init` runs forever:

```
web_1               |   File "/openverse_api/catalog/api/serializers/audio_serializers.py", line 214, in AudioWaveformSerializer
web_1               |     points = serializers.ListField(serializers.FloatField(min_value=0, max_value=1))
web_1               | TypeError: ListField.__init__() takes 1 positional argument but 2 were given
```

However, this approach does match what I've seen done for volumes for these services, so I think they make sense. The volumes are also correctly being created and torn down, even if I can't get the web container to run.

**Review by krysal — APPROVED** [review]
It does work for me. Perhaps we should use `stop` instead of `down` to not delete the container also, going along the same vein of this change.

**Review by zackkrida — APPROVED** [review]
Nice! Can confirm that the data is preserved and the volumes are created successfully:
```shell
❯ docker volume list | rg 'api_'
local     api_api-postgres
local     api_catalog-postgres
local     api_es-data
```

**Comment by zackkrida** [comment]
@sarayourfriend does `just down && just recreate && just init` remove that error?

**Comment by AetherUnbound** [comment]
> It does work for me. Perhaps we should use `stop` instead of `down` to not delete the container also, going along the same vein of this change.

I have to admit, I don't use stop that frequently :sweat_smile: Maybe I should, but it seems to be part of the "docker-compose paradigm" to use `up` and `down`!

**Pull request merged**
