### PR TITLE
Added categories.py in constant modules to store different categories.

### PR DESCRIPTION
**Pull request by ritikBhandari**
Successfully stored the 2 categories in ```categories.py ```module.
Also,imported the 'categories' from ```categories.py``` to use them wherever they were previously used.

### CODE REVIEW

**Comment by dhruvkb** [comment]
@ritikBhandari I think there has been a miscommunication here.

The goal was not to move the char fields out of the serializer into constants. The goal was to create new constants for the categories. Something similar to 
```py
class AudioCategories(models.TextChoices):
    AUDIOBOOK = 'audiobook'
    PODCAST = 'podcast'
    # ...

class ImageCategories(models.TextChoices):
    # ...
```
You can see the actual constant names in the serializers listed in the issue.

Then we update the serializer fields to use these constants.
```py
categories = serializers.ChoiceField(
    # ...
    choices=AudioCategories.choices,
)

**Review by dhruvkb — CHANGES_REQUESTED** [review]
@ritikBhandari I think there has been a miscommunication here.

The goal was not to move the char fields out of the serializer into constants. The goal was to create new constants for the categories. Something similar to 
```py
class AudioCategories(models.TextChoices):
    AUDIOBOOK = 'audiobook'
    PODCAST = 'podcast'
    # ...

class ImageCategories(models.TextChoices):
    # ...
```
You can see the actual constant names in the serializers listed in the issue.

Then we update the serializer fields to use these constants.
```py
categories = serializers.ChoiceField(
    # ...
    choices=AudioCategories.choices,
)

**Comment by zackkrida** [comment]
Hi @@ritikBhandari, have you had a chance to see @dhruvkb's review comments? If you'd like to continue working on this just let us know, otherwise we can see if someone else would like to make the necessary edits. Thank you!

**Comment by ritikBhandari** [comment]
Hi @zackkrida. Sorry actually I was involved in other projects so didn't have time to look on this issue. U can assign someone else because i'll need some time to get back to this.
Thank You.

**Comment by AetherUnbound** [comment]
Closing in favor of #589

**Pull request closed without merging**
