### PR TITLE
Update page_count calculation to fix off-by-one issue

### LINKED ISSUE #172: [Bug] Page count is off by one in the API
## Description
The API calculates page count as `int(results / page_size)` which leads to the page size being one less than the correct value.

## Reproduction
Query the search endpoints for images or audio and see the result count vs. page count. There is a discrepancy there.

## Expectation
Page count should be the correct number of pages in the result.

## Additional context
The error originates here:
https://github.com/WordPress/openverse-api/blob/9c8987c942cf4cba5a121be4519b0f2354273f50/openverse-api/catalog/api/controllers/search_controller.py#L487

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### LINKED ISSUE #196: Dead link filtering reduces number of queryable pages
## Description

The dead link filtering algorithm significantly limits the pages that can be retrieved.

## Reproduction

0. Go to audio search endpoint: `http://localhost:8000/v1/audio/`. Note the number of pages.
1. Go to a page number that's quite high but less than 250, like 200: `http://localhost:8000/v1/audio/?page=200`
2. See the deep pagination error. This should not be happening.

## Expectation

Page count calculation should be correct and should allow pagination upto the stated limit.

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by ritesh-pandey**
Page count was off by one in some cases. Add a condition to check if
results is divisible by page_size. If not, increment page_count by 1.

## Fixes

<s>Fixes</s> #196 by @dhruvkb
Fixes #172 by @dhruvkb

## Description
Adds a check in result count calculation. If result_count is not completely divisible by page_size, increment page_count by one.  

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main` or `master`).
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — APPROVED** [review]
Thank you!

**Comment by ritesh-pandey** [comment]
Also fixes #172

**Comment by dhruvkb** [comment]
I'm so stupid I opened two issues for one bug. Thanks @ritesh-pandey!

**Review by dhruvkb — APPROVED** [review]
This fixes the pagination off-by-one issue.

**Pull request merged**
