### PR TITLE
Pass user to ingestion-server and indexer_worker containers

### PR DESCRIPTION
**Pull request by krysal**
## Fixes

Follow up on #820.

## Description

The fix on #862 probed to reduce the number of failed remove operations for the **Publish developer docs** job. Before we were getting errors for files under the `api/` folder, and currently the problem persists but only for files under the `ingestion_server` so I believe adding the same user to those containers should fix it.

Compare jobs before and after #820:
- https://github.com/WordPress/openverse-api/runs/7617116799?check_suite_focus=true
- https://github.com/WordPress/openverse-api/runs/7978840111?check_suite_focus=true

## Checklist

- [ ] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [ ] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by sarayourfriend — COMMENTED** [review]
FWIW this reasoning and PR makes sense to me @krysal

**Review by dhruvkb — APPROVED** [review]
The reason looks reasonable and, if that is indeed the case, the PR should fix it.

**Comment by zackkrida** [comment]
This is looking right to me, shall we mark it as ready for review @krysal ?

**Comment by krysal** [comment]
The changes made several tests fail, I haven't looked into it yet, so I drafted it to prevent re-ping reviewers until it is fixed.

**Review by AetherUnbound — APPROVED** [review]
🚀 📄

**Pull request merged**
