### PR TITLE
Add `peaks` query param for audio requests

### LINKED ISSUE #917: Make the waveform peaks optional
## Problem

We include all the peaks from every audio track that has them previously generated in audio responses (on list & details endpoints). This consumes tons of bytes in network responses and with the default `page_size=20` it can even freeze the browser for a few seconds. Users might not need or want the peaks in every request so making it conditional with a query parameter can improve the experience.

## Implementation

- [x] 🙋 I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by krysal**
## Fixes

Fixes #917 by @krysal
Related to #557 by @AetherUnbound 

## Description

This PR adds the `peaks` query param to make the inclusion of waveform peaks optional. It defaults to `False` to avoid sending large amounts of data unnecessarily.

We originally talked about naming the param `waveform` but that is the field name of the waveform link in the response, so `peaks` turned out to be more appropiate.

## Testing Instructions

To test manually follow these steps:
1. Change to this branch
2. Make a new `sample_data/sample_audio.csv` with just a few entries, I just copied the first ~30 or so of the original file
3. Run `just recreate`
4. Run `just dj generatewaveforms`
5. Try the API with the new query parameter
  - http://localhost:50280/v1/audio/
  - http://localhost:50280/v1/audio/?peaks=true
  - http://localhost:50280/v1/audio/?peaks=0
  - same for the audio detail :)

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by zackkrida — APPROVED** [review]
It's looking great, Krystle! Works correctly locally.

**Review by stacimc — APPROVED** [review]
Looks good to me, and tested great :)

**Comment by zackkrida** [comment]
Oh, one thing I missed here, @krysal. Can you confirm this works the same way the other boolean parameter, `mature` does? Do they both need to be set to the string `true` or `false` or is the _presence_ of the query param all it needs? It looks like this PR requires the 'true' string but I can't remember for mature.

**Comment by krysal** [comment]
@zackkrida Yes, they work the same way, requiring a valid boolean value (e.g. `true`, `t`, or `1` and the same for falsy values) if it's specified, when not (if you make a request with no value `?mature=` ), they will go with defaults: `False` in both cases.

**Pull request merged**
