### PR TITLE
Add trailing slashes to URL conf paths

### PR DESCRIPTION
**Pull request by dhruvkb**
## Description

This PR adds trailing slashes to two URLs that did not have those. This makes them more consistent with the rest of the URLs in the codebase and also makes it possible to call them from the frontend (which mandatorily suffixes a slash to API calls).

It will not affect any existing users as `APPEND_SLASH` setting should ideally redirect them to the right address.

## Testing Instructions

0. Check out the branch and run the dev server `just up`.
1. Try visiting the changed URLs (with and without the slash).
2. Observe redirects when you visit the URL without the slash.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by sarayourfriend — APPROVED** [review]
Change looks fine to me but... I have to wonder.... are we being too fiddly with these trailing slashes? What is the reason to be so strict about them? It's caused issues with users trying to use the API as well, we've gotten at least one email that I'm aware of from someone confused by this.

**Comment by dhruvkb** [comment]
I'm not a hundred percent sure of the reason but I've always preferred trailing slashes after URLs because Django will automatically append those if you miss it but will never strip them if you add one accidentally.

Also, the URL config looks much cleaner and nests easily if each path segment ends with a slash, so for consistency, it's generally easier to just add the slash everywhere.

**Comment by dhruvkb** [comment]
I don't think I've seen any linter that can catch missing trailing slashes but I'll definitely go through the URLs manually and ensure we're not missing any.

**Comment by sarayourfriend** [comment]
A unit test might be able to do it though, if not a linter (which I also doubt is able to given the programatic nature of these)?

**Comment by sarayourfriend** [comment]
@obulat suggested that for validation we can use the `generateschema` command and then pass it through a validation. Olga, can you share what tool you were using to validate the generated schema?

**Comment by sarayourfriend** [comment]
@dhruvkb I opened this PR with a proposal of a start to how we might validate it using Olga's approach: https://github.com/WordPress/openverse-api/pull/806

I'm not sure if it's the best way though and it doesn't appear to be currently catching the lack of trailing slashes on some endpoints, so it doesn't even seem to accomplish what we want from it anyway.

**Comment by dhruvkb** [comment]
@sarayourfriend IIUC the specifications that the tool validates only check for a leading slash and not the trailing one.

**Comment by sarayourfriend** [comment]
We could write our own validation against the generated YAML schema to check for the trailing slashed at least... in addition to spec based validation (which seems useful anyway?).

We'd need to extend the `validateopenapischema` command to check the parsed YAML for trailing slashes and raise an error when appropriate. Do you think that could work?

**Review by stacimc — APPROVED** [review]
This looks good to me. I'd be fine with merging this and continuing the unit testing work in a separate PR since it's an interesting problem all on its own; what do y'all think?

**Comment by sarayourfriend** [comment]
+1, Staci. Makes sense to me!

**Pull request merged**
