### PR TITLE
Fix CI issues is audio models

### PR DESCRIPTION
**Pull request by dhruvkb**
The PR #81 failed CI checks **after** being merged. This PR addresses those check failures.

### CODE REVIEW

**Comment by dhruvkb** [comment]
^ Tests pass now.

**Review by zackkrida — APPROVED** [review]
Thank you

**Review by obulat — APPROVED** [review]
Thank you for the quick fix, sorry for causing the issues with merging :(

**Comment by dhruvkb** [comment]
No problem at all! I should have run the tests on my branch **before** the merge rather than after.

**Pull request merged**
