### PR TITLE
Fix invalid UUID breaking related images query

### PR DESCRIPTION
**Pull request by obulat**
## Fixes

Related to #729 by @AetherUnbound 

## Description

This PR uses @krysal 's [suggestion](https://github.com/WordPress/openverse-api/issues/729#issuecomment-1163336180) to add an IndexError handling for when there are no `hits` in the search controller:
https://github.com/WordPress/openverse-api/blob/7414174a16ba4cbd6af70773ce6d19b92b0e96de/api/catalog/api/controllers/search_controller.py#L344

## Testing Instructions

On main, if you go to `http://localhost:8000/v1/images/000000000000000000000000000000000000/related/`, you would get a 500 error.
On this branch, you should get a 404.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dhruvkb — APPROVED** [review]
This is a good fix. We should still tighten up the lookup regex for good measure.

**Comment by obulat** [comment]
> Also, do you know why something that looks like a valid UUID (follows the pattern) doesn't cause the 500? Why doesn't it throw an IndexError as well like the same-length-but-not-UUID-pattern string does when queried for?

@sarayourfriend, actually, that's not the case, but it took me some time to figure it out :)
The example you gave in the issue (`da5cb478-c093-4d62-b721-cda18797e3fz`) looks like UUID for humans, because we don't notice that `z`(the last letter of the string) is not in the pattern, it's only `a-f` for the hex numbers.

**Comment by sarayourfriend** [comment]
Ah!! I forgot that UUID had rules :sweat_smile: Good catch! Sorry for the false lead :scream:

**Comment by obulat** [comment]
> Ah!! I forgot that UUID had rules 😅 Good catch! Sorry for the false lead 😱

It was actually a great opportunity to learn more about what's happening when we search for something 👍

**Pull request merged**
