### PR TITLE
Make link validation expiry maximally configurable

### PR DESCRIPTION
**Pull request by sarayourfriend**
## Fixes

Fixes #878 by @obulat 

## Description

An alternative version of my [other PR to address this issue](https://github.com/WordPress/openverse-api/pull/878) that introduces maximal configurability into the cache times so that we can tweak times for any status code without having to make new releases.

## Testing Instructions

Follow the test instructions in https://github.com/WordPress/openverse-api/pull/878. They are the same here, however in this PR you should also test adding a new environment variable for a status that is not included in the list of default statuses and confirming that it has the expiration used for it.

Also check out the unit tests for the configuration class and confirm they are sufficiently comprehensive.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by obulat — APPROVED** [review]
Link validation expiry configuration becomes really flexible, and the tests are great!

Do we need to add some kind of 'expiration' fixture to other tests to make them pass? Why is the failing test currently failing?

**Comment by sarayourfriend** [comment]
@obulat a lot of tests are failing due to #866 I think. It's hard to tell because for some reason due to the test configuration the tests only write out "AssertionError" instead of the actual error contents.

**Comment by sarayourfriend** [comment]
Drafting this to prevent PR review pings. I'll let folks decide what to do with this while I'm on vacation over the next three weeks :wave:

**Comment by AetherUnbound** [comment]
I'm undrafting this, I like the new changes a ton! I've added some small things, including some documentation in `settings.py` (since that's typically where I'm most likely to look when figuring out what settings I can modify using env variables).

**Review by zackkrida — APPROVED** [review]
LGTM. This is quite cool. I tested by removing the status default for `200` and adding my own `LINK_VALIDATION_CACHE_EXPIRY__200='{"days": 1}` to the docker.env file. Confirming this worked with the redis instructions in the other PR worked well.

**Pull request merged**
