### PR TITLE
Rename the API directory to `api/`

### PR DESCRIPTION
**Pull request by dhruvkb**
## Description

For maintaining consistency with `ingestion_server` and `analytics`, the prefix `openverse-` has been dropped from the `openverse-api` subproject to change it to just `api`.

## Testing Instructions

This is a name change so passing tests in CI should be good enough to validate the correctness of the code. Updating the docs is trickier. So a manual review of those changes is good to have.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by dhruvkb** [comment]
Please refer to [the successful workflow run](https://github.com/WordPress/openverse-api/actions/runs/1638600802). Hopefully it reduces the need to check out and test the PR locally.

**Review by AetherUnbound — CHANGES_REQUESTED** [review]
Fully support this! I'm noticing the following instances of `openverse_api` still exist in the repo:

```
./justfile:53:    cp openverse_api/env.template openverse_api/.env
./api/catalog/settings.py:85:    AWS_STORAGE_BUCKET_NAME = config("LOGOS_BUCKET", default="openverse_api-logos-prod")
./api/Dockerfile:66:    && mkdir -p /var/log/openverse_api/openverse_api.log
./CONTRIBUTING.md:37:1. Change directory to `openverse_api`
./CONTRIBUTING.md:40:cd openverse_api
```

The Django settings one probably doesn't need to change, but I think the others might?

**Comment by dhruvkb** [comment]
@AetherUnbound 
- I intentionally left the `openverse_` in the log directory path because what API referred to in `/var/log/api` was very ambiguous
- the `CONTRIBUTING.md` file is out of date in a lot of places, that one will need a major rewrite (either as an `.md` file or in Sphinx as a part of #427).

**Review by AetherUnbound — APPROVED** [review]
Got it, those both make sense!

**Review by zackkrida — APPROVED** [review]
```
❯ rg 'openverse_api'
CONTRIBUTING.md
37:1. Change directory to `openverse_api`
40:cd openverse_api

api/Dockerfile
66:    && mkdir -p /var/log/openverse_api/openverse_api.log

api/catalog/settings.py
89:    AWS_STORAGE_BUCKET_NAME = config("LOGOS_BUCKET", default="openverse_api-logos-prod")
```

Not seeing any instances of `openverse_api` other than those discussed, excellent!

**Pull request merged**
