### PR TITLE
License validation does not work correctly for non-lower-case strings #740

### LINKED ISSUE #740: License validation does not work correctly for non-lower-case strings
## Description

When filtering a search by `license`, and use a non-lower-cased license, you don't receive an error message, but you also don't get any results.

## Reproduction

1. Search for images with an uppercase license filter: http://localhost:8000/v1/images/?q=cat&license=BY-SA
2. See error: You'll get no results, and no errors. If you use an invalid license string, then you'd get an error:
```
{
    "detail": {
        "license": [
            "License 'by-sta' does not exist."
        ]
    }
}
```
## Additional context

I'm not sure what the best solution here would be:
- consider any case of license valid if it's a valid license when lowercased(`license=BY-sa` returns all items with `by-sa` license)
- consider the licenses invalid if they have incorrect case (`license=BY` throws an error)

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by raghuvar-arora-au2**
## Fixes
Fixes #740  by @obulat 

## Description
This PR fixes the issue of the case sensitivity of the license filter. It only required a tiny change in the serialzier.  

## Testing Instructions
on main, Both endpoints `http://localhost:8000/v1/images?license=cC0,By` and `http://localhost:8000/v1/images?license=cc0,by` returns the same output

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by dhruvkb — COMMENTED** [review]
@raghuvar-arora-au2 could you add some documentation about the new function and why it was implemented this way instead of lowercasing the input in the serializer.

The description in issue #740 made me think that lowercasing the input (suggestion no. 1) was a viable solution.

**Comment by raghuvar-arora-au2** [comment]
That is what I wanted to do, initially, but couldn't figure it out. Can you point me to the file that I should look into, please?

**Comment by raghuvar-arora-au2** [comment]
I made the changes. thanks

**Comment by raghuvar-arora-au2** [comment]
Can someone tell me why I'm failing the checks?

**Comment by AetherUnbound** [comment]
> Can someone tell me why I'm failing the checks?

The ingestion server tests seem to be unrelated and the result of #715. Rerunning that action should fix the intermittent issue.

As for the linting step, we have a few `just` recipes that are run to ensure the code passes certain static checks:

https://github.com/WordPress/openverse-api/blob/2e85caf7aede8aaf9d77cd5cb050f50b860ee58e/justfile#L85-L91

Unfortunately we don't have documentation describing how to set that up locally as a contributor! I've made #772 to track this, thanks for helping us identify it 😄 For now you can run `just precommit` and `just lint` to identify/correct the issues locally and commit the changes it makes.

The docs preview shouldn't be running 🤔 We tried to address that in #693 but I guess our logic there was somehow incorrect 😓 that failure can be ignored for now!

**Comment by raghuvar-arora-au2** [comment]
@AetherUnbound can you review this, please?

**Review by sarayourfriend — APPROVED** [review]
Madison is out on vacation for the next couple weeks.

This LGTM! Thanks @raghuvar-arora-au2! Once @obulat or @dhruvkb approves this we'll merge the PR for you.

**Review by obulat — APPROVED** [review]
Thank you for your contribution, @raghuvar-arora-au2! The code solves the issue, and the tests make sure we don't regress 👍

**Pull request merged**
