### PR TITLE
delete resendoauthverificationrequest and resendoauthverificationrequest_test

### LINKED ISSUE #1042: Remove resendverificationemails command and tests
## Problem

Now that verification emails are sent and the issue is fixed, we can remove this command. Critically, we can remove it's slow-running tests.

## Description

Remove the command and the associated tests. If we ever need it again for some reason we can revert the change.

## Implementation

- [ ] 🙋 I would be interested in implementing this feature.

### PR DESCRIPTION
**Pull request by sahil-R**
## Fixes

Fixes #1042  by @sarayourfriend 

## Description

since the. Verification emails are being sent now, there is no use of the resendoauthverificationrequest command, and it's test cases. So we can remove these files from their respective directories. This branch removes those files. 

**Please note if you run 'just api-test' too frequently, you'll fail some test cases as they revert with a status code of 429, which is too many requests in a limited time, so you can wait for a couple of minutes and test again it will work fine then.**

## Testing Instructions
'just api-test' will no more run for resendoauthverification_test.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like
      `Update index.md`).
- [x] My pull request targets the _default_ branch of the repository (`main`) or
      a parent feature branch.
- [ ] My commit messages follow [best practices][best_practices].
- [ ] My code follows the established code style of the repository.
- [x] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible
      errors.

[best_practices]:
  https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by sahil-R** [comment]
Hey @sarayourfriend ,i have created this draft PR also i am attaching a screenshot of what i have also written in the description of the draft pr
Screenshot 2022-12-16 at 1 04 10 PM
7-85a5-88a55ff5e63e.png">

**Comment by sahil-R** [comment]
Hey @sarayourfriend any update??

**Comment by sarayourfriend** [comment]
Hi @sahil-R, I (and many other Openverse maintainers) do not check the Openverse repositories over the weekend. I ask that you be patient with us as well, as it's an active project with lots going on and we sometimes take a moment to get around to things like this. That being said, thanks for the original direct ping as it made this easy to find :slightly_smiling_face: 

Please feel free to ignore the repeated test runs causing 429s. We have an issue that would address this problem but needs more thinking before it can be implemented #866. With #1027 merged, it should be slightly easier to implement it, so we might be able to revisit that issue soon.

In any case, so long as you've deleted the two files mentioned in the issue discussion, which you have done here, then this PR will be easy to approve once it is undrafted. Feel free to undraft it at your leisure.

**Comment by sahil-R** [comment]
> Hi @sahil-R, I (and many other Openverse maintainers) do not check the Openverse repositories over the weekend. I ask that you be patient with us as well, as it's an active project with lots going on and we sometimes take a moment to get around to things like this. That being said, thanks for the original direct ping as it made this easy to find 🙂
> 
> Please feel free to ignore the repeated test runs causing 429s. We have an issue that would address this problem but needs more thinking before it can be implemented #866. With #1027 merged, it should be slightly easier to implement it, so we might be able to revisit that issue soon.
> 
> In any case, so long as you've deleted the two files mentioned in the issue discussion, which you have done here, then this PR will be easy to approve once it is undrafted. Feel free to undraft it at your leisure.

Hey @sarayourfriend, sorry for the messages, I had university exams aligned so I thought I'll finish it before that rest said , I'll open a pr ,thankyou for your time and once again i apologise for disturbing you out of time.

**Pull request closed without merging**
