### PR TITLE
Run CI/CD on every pull request

### LINKED ISSUE #443: Run integration tests on all PRs
## Description
Currently the integration tests only run on PRs that target `main`. This means PRs targeting another branch don't get tested until that branch gets merged and the base is automatically changed to `main`.

## Expectation

Tests should run on all PRs so that a all PRs in a chain have a good amount of confidence that they don't break anything.

## Additional context

<s>To prevent merge conflicts in many open PRs, this is blocked till #438 is merged.</s>

## Resolution

- [ ] 🙋 I would be interested in resolving this bug.

### PR DESCRIPTION
**Pull request by AetherUnbound**
## Fixes

Fixes #443 by @dhruvkb

## Description

This PR removes the `main` constraint for PR triggers in the CI/CD workflow so that all PRs run the docker building, testing, and integration test steps.

## Testing Instructions

We could potentially open a PR _onto_ this PR if we wanted to test that it works.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by sarayourfriend — APPROVED** [review]
LGTM! Glad it was this straight forward 🙂 

For reference for anyone else, here's the documentation for the `pull_request` event (which confused me at first): https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request

**Comment by AetherUnbound** [comment]
Looks like things are working okay! (See #508)

**Review by zackkrida — APPROVED** [review]
LGTM!

**Comment by sarayourfriend** [comment]
@AetherUnbound merging this as it's been approved for a while and we've confirmed it works.

**Comment by AetherUnbound** [comment]
My goodness, thanks for doing that! Sorry I missed this, I thought I didn't have 2 reviews.

**Pull request merged**
