### PR TITLE
Update ES indices and search controller

### PR DESCRIPTION
**Pull request by dhruvkb**
## Description

This PR
- changes the ES mapping mode from `dynamic` (default) to `false` (so that any unmapped fields are stored but not indexed)
- removes unnecessary schema mappings, changing them to purely stored fields
- converts some fields from text+keyword to just keyword
- moves hardcoded dictionary to external YAML files

This is an updated version of #684, which has diverged too much from `main` to salvage. Also many of the changes in that PR have been broken up and merged in chunks in other PRs.

## Testing Instructions

Since CI is passing, there is little reason to worry that any core functionality is broken. Also there is a comprehensive deployment plan for this PR which will ensure that there is no downtime involved in the deployment.

To verify,

0. Delete all existing data and volumes: `just down -v`. 
1. Check out the PR and bring up all services: `just init`
2. Verify endpoints for list, search and detail for audio and images.
3. Specifically verify that the information about extensions and filetypes is valid (that was a point of conflict during merge).

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the *default* branch of the repository (`main`) or a parent feature branch.
- [x] My commit messages follow [best practices][best_practices].
- [x] My code follows the established code style of the repository.
- [ ] I added or updated tests for the changes I made (if applicable).
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

[best_practices]:https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project#_commit_guidelines

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by zackkrida** [comment]
@dhruvkb do you think this should be closed or picked back up?

**Comment by dhruvkb** [comment]
@zackkrida picked up for sure, now that the ES utilisation is under control, deploying the new indices should be the next target.

**Comment by AetherUnbound** [comment]
@dhruvkb It looks like this may have diverged from main, does it still make sense to target this work soon? If not, should we close this PR?

**Comment by dhruvkb** [comment]
Yep, I'll close it for now and we can reopen it when we prioritise this project.

**Pull request closed without merging**
